'use client';
import './globals.css'
import Header from '../components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html 
    lang="en"
    className={localStorage.getItem("darkMode")=== "true" ? "dark" : "light"}
    >
      <body className='dark:bg-slate-900 dark:text-white'>
        <Header />
        {children}
      </body>
    </html>
  )
}
